Update the tests to support both bro and zeek commands

diff --git a/tests/Scripts/get-zeek-env b/tests/Scripts/get-zeek-env
--- a/tests/Scripts/get-zeek-env
+++ b/tests/Scripts/get-zeek-env
@@ -19,18 +19,31 @@ if [ -n "${zeek_dist}" ]; then
 else
     # Use Zeek installation for testing. In this case zeek-config must be in PATH.
     if ! which zeek-config >/dev/null; then
-        echo "zeek-config not found" >&2
-        exit 1
-    fi
+        if ! which bro-config >/dev/null; then
+            echo "zeek-config and bro-config not found" >&2
+            exit 1
+        fi
+        if [ "$1" == "zeekpath" ]; then
+            bro-config --bropath
+        elif [ "$1" == "zeek_plugin_path" ]; then
+            ( cd ${base}/../../ && pwd )
+        elif [ "$1" == "path" ]; then
+            echo ${PATH}
+        else
+            echo "usage: `basename $0` <var>" >&2
+            exit 1
+        fi
 
-    if [ "$1" = "zeekpath" ]; then
-        zeek-config --zeekpath
-    elif [ "$1" = "zeek_plugin_path" ]; then
-        ( cd ${base}/../.. && pwd )
-    elif [ "$1" = "path" ]; then
-        echo ${PATH}
-    else
-        echo "usage: `basename $0` <var>" >&2
-        exit 1
+   else
+        if [ "$1" = "zeekpath" ]; then
+            zeek-config --zeekpath
+        elif [ "$1" = "zeek_plugin_path" ]; then
+            ( cd ${base}/../.. && pwd )
+        elif [ "$1" = "path" ]; then
+            echo ${PATH}
+        else
+            echo "usage: `basename $0` <var>" >&2
+            exit 1
+        fi
     fi
 fi
